-- public.tb_service_status definition

-- Drop table

-- DROP TABLE public.tb_service_status;

CREATE TABLE public.tb_service_status (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	uf_autorizador varchar(255) NULL,
	data_consulta timestamp NULL,
	status_servico varchar(255) NULL,
	indisponivel varchar(255) NULL,
	CONSTRAINT tb_service_status_pkey PRIMARY KEY (id)
);

INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(1, 'AM', '2022-06-02 19:27:10.241', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(2, 'BA', '2022-06-02 19:27:10.349', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(3, 'GO', '2022-06-02 19:27:10.369', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(4, 'MG', '2022-06-02 19:27:10.380', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(5, 'MS', '2022-06-02 19:27:10.400', 'linhaImparCentralizada', Indisponivel);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(6, 'MT', '2022-06-02 19:27:10.420', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(7, 'PE', '2022-06-02 19:27:10.431', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(8, 'PR', '2022-06-02 19:27:10.451', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(9, 'RS', '2022-06-02 19:27:10.482', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(10, 'SP', '2022-06-02 19:27:10.493', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(11, 'SVAN', '2022-06-02 19:27:10.511', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(12, 'SVRS', '2022-06-02 19:27:10.521', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(13, 'SVC-AN', '2022-06-02 19:27:10.534', 'imagens/bola_verde_P.png', NULL);
INSERT INTO public.tb_service_status
(id, uf_autorizador, data_consulta, status_servico, indisponivel)
VALUES(14, 'SVC-RS', '2022-06-02 19:27:10.544', 'imagens/bola_verde_P.png', NULL);

